### ISSUE TITLE
I am having an issue building

### ISSUE THREAD

**Issue by unlimitedcoder2** [nx-python/PyNX#13]
I am building on windows 10
![image](https://user-images.githubusercontent.com/16884313/51833767-45335c00-22f0-11e9-85fb-b54681237e01.png)

full log :
make --no-print-directory  -C python_build
cd Python-3.5.3 && make  --no-print-directory LIBRARY="libpython3.5.a" LDLIBRARY="libpython3.5.a" libpython3.5.a && cd .. && cp Python-3.5.3/libpython3.5.a . && touch linkPY
make : Makefile:1759: warning: overriding recipe for target 'Modules/_math.o'
At line:1 char:1
+ make > log.txt 2>&1
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Makefile:1759: ...odules/_math.o':String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Makefile:609: warning: ignoring old recipe for target 'Modules/_math.o'
Makefile:1762: warning: overriding recipe for target 'Modules/_math.o'
Makefile:1759: warning: ignoring old recipe for target 'Modules/_math.o'

aarch64-none-elf-gcc -c -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -g -Wall -O2 -ffunction-sections -DDISABLE_TRACEMALLOC -march=armv8-a -mtune=cortex-a57 -mtp=soft -fPIE  -I/opt/devkitpro/portlibs/switch/include -I/opt/devkitpro/libnx/include -I/home/unlim/PyNX/python_build/ -DSWITCH      -I. -I./Include    -DPy_BUILD_CORE -o Python/ceval.o Python/ceval.c
In file included from Python/ceval_gil.h:62,
                 from Python/ceval.c:300:
Python/condvar.h: In function 'PyCOND_INIT':

Python/condvar.h:153:5: error: too many arguments to function 'condvarInit'
     condvarInit(cond, mut);
     ^~~~~~~~~~~

In file included from Python/condvar.h:116,
                 from Python/ceval_gil.h:62,
                 from Python/ceval.c:300:
C:/devkitPro/libnx/include/switch/kernel/condvar.h:19:20: note: declared here
 static inline void condvarInit(CondVar* c)
                    ^~~~~~~~~~~

In file included from Python/ceval_gil.h:62,
                 from Python/ceval.c:300:
Python/condvar.h: In function 'PyCOND_TIMEDWAIT':

Python/condvar.h:169:36: warning: passing argument 2 of 'condvarWaitTimeout' makes pointer from integer without a cast [-Wint-conversion]
     r = condvarWaitTimeout((cond), ns);
                                    ^~

In file included from Python/condvar.h:116,
                 from Python/ceval_gil.h:62,
                 from Python/ceval.c:300:
C:/devkitPro/libnx/include/switch/kernel/condvar.h:32:46: note: expected 'Mutex *' {aka 'int *'} but argument is of type 'u64' {aka 'long unsigned int'}
 Result condvarWaitTimeout(CondVar* c, Mutex* m, u64 timeout);
                                       ~~~~~~~^

In file included from Python/ceval_gil.h:62,
                 from Python/ceval.c:300:
Python/condvar.h:169:9: error: too few arguments to function 'condvarWaitTimeout'
     r = condvarWaitTimeout((cond), ns);
         ^~~~~~~~~~~~~~~~~~
In file included from Python/condvar.h:116,
                 from Python/ceval_gil.h:62,
                 from Python/ceval.c:300:
C:/devkitPro/libnx/include/switch/kernel/condvar.h:32:8: note: declared here
 Result condvarWaitTimeout(CondVar* c, Mutex* m, u64 timeout);
        ^~~~~~~~~~~~~~~~~~

In file included from Python/ceval_gil.h:62,
                 from Python/ceval.c:300:
Python/ceval_gil.h: In function 'drop_gil':

Python/condvar.h:160:33: error: too few arguments to function 'condvarWait'
 #define PyCOND_WAIT(cond, mut)  condvarWait((cond))
                                 ^~~~~~~~~~~
Python/ceval_gil.h:100:9: note: in expansion of macro 'PyCOND_WAIT'
     if (PyCOND_WAIT(&(cond), &(mut))) { \
         ^~~~~~~~~~~
Python/ceval_gil.h:208:13: note: in expansion of macro 'COND_WAIT'
             COND_WAIT(switch_cond, switch_mutex);
             ^~~~~~~~~

In file included from Python/condvar.h:116,
                 from Python/ceval_gil.h:62,
                 from Python/ceval.c:300:
C:/devkitPro/libnx/include/switch/kernel/condvar.h:41:22: note: declared here
 static inline Result condvarWait(CondVar* c, Mutex* m)
                      ^~~~~~~~~~~

make[2]: *** [Makefile:1547: Python/ceval.o] Error 1

make[1]: *** [Makefile:88: linkPY] Error 2

make: *** [Makefile:143: cpython] Error 2

**Comment by unlimitedcoder2** [comment]
[log.txt](https://github.com/nx-python/PyNX/files/2802735/log.txt)

**Comment by DavidBuchanan314** [comment]
I'm not sure what the actual cause of the issue is, but I'd recommend building from WSL rather than native windows. (Or better yet, on a Linux machine)

**Comment by DavidBuchanan314** [comment]
If you can fix build on Win10, PRs welcome

**Comment by elnardu** [comment]
libnx has changed some apis, and pynx code was not updated

**Comment by unlimitedcoder2** [comment]
![image](https://user-images.githubusercontent.com/16884313/51851463-dbc94280-231b-11e9-9eb2-054a922a05df.png)

https://github.com/nx-python/PyNX/issues/7
I saw that but because I am using ubuntu I cannot use dkp-pacman or pacman

**Comment by elnardu** [comment]
You do not have devkitpro installed?

https://devkitpro.org/wiki/devkitPro_pacman

**Comment by unlimitedcoder2** [comment]
![image](https://user-images.githubusercontent.com/16884313/51851945-e6380c00-231c-11e9-9ea1-9ec63e91a127.png)
I do but I don't have pacman to install the zlib package.
btw the previous screenshot was of an ubuntu server because https://github.com/nx-python/PyNX/issues/13#issuecomment-458170648 so I thought I would try a real linux machine but I do have pacman on my windows 
![image](https://user-images.githubusercontent.com/16884313/51852067-30b98880-231d-11e9-9967-80504f879428.png)

**Comment by unlimitedcoder2** [comment]
https://github.com/devkitPro/buildscripts I used the buildscript but when I installed https://github.com/devkitPro/pacman/releases/tag/devkitpro-pacman-1.0.1 It allowed me to install switch-zlib however It still doesn't work 
![image](https://user-images.githubusercontent.com/16884313/51854813-9f014980-2323-11e9-9505-5c13554fc21e.png)

**Comment by elnardu** [comment]
Can you do `ls /home/ubuntu/.devPro/portlibs/switch/include` ?

**Comment by unlimitedcoder2** [comment]
![image](https://owo.oooooooooooooo.ooo/i/wunv.png)

**Comment by elnardu** [comment]
`dkp-pacman -Ql switch-zlib`

**Comment by unlimitedcoder2** [comment]
![image](https://owo.oooooooooooooo.ooo/i/jxic.png)

**Comment by elnardu** [comment]
Your dkp environment variables are incorrect

**Comment by unlimitedcoder2** [comment]
[log.txt](https://github.com/nx-python/PyNX/files/2808096/log.txt)
![image](https://owo.oooooooooooooo.ooo/i/c1oz.png)

I have now used the pacman installed version of switch-dev and switch-zlib and am still having the error. Even on linux

**Comment by cristianmiranda** [comment]
Hi!. I'm building on macOS and having the same issue. Any progress on this one? Thanks!

**Comment by unlimitedcoder2** [comment]
I will try building it tomorrow and see if I still have the same issue

**Comment by cristianmiranda** [comment]
@unlimitedcoder2 Did you run into the same issue?

**Comment by unlimitedcoder2** [comment]
![](https://i.imgur.com/a69ovTo.png) don't think it is the same error

**Comment by cristianmiranda** [comment]
You're not on Windows anymore, are you?

**Comment by unlimitedcoder2** [comment]
Was on linux before aswell

**Comment by ioistired** [comment]
> don't think it is the same error

I get this same error.

**Comment by unlimitedcoder2** [comment]
I have never been able to successfully compile this

**Comment by shz224** [comment]
I have problem with building too. I used `make` on Windows after install devkitPro.
![image](https://user-images.githubusercontent.com/48586099/87236880-15fba680-c421-11ea-92fb-9c7b6131d1c2.png)
Could anyone help me please?

**Comment by d1ddle** [comment]
Was the issue ever solved?

Edit: 
I have no idea what the problem might be but here is what (I think) I know:
May be something to do with https://bugs.python.org/issue30854
`ceval.o` is never built, and so can't be found. Then raises the error:
```
make[2]: *** [Makefile:1547: Python/ceval.o] Error 1
make[1]: *** [Makefile:88: linkPY] Error 2
make: *** [Makefile:143: cpython] Error 2
```

In line 1:
"Most commands don't bother with distinctions other than 0 = success, anything else = failure" (https://unix.stackexchange.com/questions/18807/where-can-i-find-a-list-of-make-error-codes)
So the first line is a build error.

The second line is irrelevant (Meaning I can't find a reason for this)

The third line is a cpython error, which is actually the source code for python.
And in python, error 2 is a file not found error, a result of the build failure:
`The Python FileNotFoundError: [Errno 2]`
Which therefore can't proceed building python-nx.

Still working on a fix though. I know nothing about C or compiling so I wouldn't get your hopes up.
This is literally all I've gathered through trial and error.
