### ISSUE TITLE
zlib.h error while building on macOS

### ISSUE THREAD

**Issue by jacobschultz** [nx-python/PyNX#7]
Hey everyone,

I'm not sure if this an issue with my machine specifically or if it's an actual issue. When compiling this by running 'make' on a mac I run into the following issue. I have python up to date, and the xcode dev tools installed. I also used brew to install gnu-sed. In the /python_build folder zlib.h is included in the zlib.c folder, but this actually lives in the /python_build/zlib folder. Could this be causing issues? Has anyone else ran into this issue? 

`
 -DDISABLE_TRACEMALLOC -march=armv8-a -mtune=cortex-a57 -mtp=soft -fPIE  -I/opt/devkitpro/portlibs/switch/include -I/opt/devkitpro/libnx/include -I/Users/jacob.schultz/Downloads/PyNX-master/python_build/ -DSWITCH      -I. -I./Include    -DPy_BUILD_CORE  -c ./Modules/binascii.c -o Modules/binascii.o
aarch64-none-elf-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -g -Wall -O2 -ffunction-sections -DDISABLE_TRACEMALLOC -march=armv8-a -mtune=cortex-a57 -mtp=soft -fPIE  -I/opt/devkitpro/portlibs/switch/include -I/opt/devkitpro/libnx/include -I/Users/jacob.schultz/Downloads/PyNX-master/python_build/ -DSWITCH      -I. -I./Include    -DPy_BUILD_CORE  -I/opt/devkitpro/portlibs/switch/include -c ./Modules/zlibmodule.c -o Modules/zlibmodule.o

./Modules/zlibmodule.c:10:10: fatal error: zlib.h: No such file or directory
 #include "zlib.h"

compilation terminated.
make[2]: *** [Modules/zlibmodule.o] Error 1
make[1]: *** [linkPY] Error 2
make: *** [cpython] Error 2
`

**Comment by elnardu** [comment]
Hey! Have you installed zlib using devkitpro's pacman?

**Comment by jacobschultz** [comment]
I have not, I used brew. Let me give that a try.

**Comment by ibussa** [comment]
I get the same error building on Windows using devkitpro and yes and I also have installed zlib.

**Comment by elnardu** [comment]
Have you done something like this?
`sudo dkp-pacman -S switch-zlib`
`pacman -S switch-zlib`
