### ISSUE TITLE
Download files via HTTP (e.g. urllib)

### ISSUE THREAD

**Issue by niemasd** [nx-python/PyNX#8]
I can't seem to find a way to download files via HTTP. I wanted to use `urllib`, but I get `OSError: [Errno 93]` when it tries to connect

**Comment by elnardu** [comment]
Сan you check if urllib works for you now?

**Comment by niemasd** [comment]
I don't have the environment set up to compile on my Mac OS X; would you mind compiling and sending the binaries? Or are there simple instructions to set up the dependencies to compile on Mac OS X?

**Comment by elnardu** [comment]
https://www.dropbox.com/sh/6gtc6w91c16wpiz/AABk3JrGca7kZuZVEurnjiysa?dl=0

**Comment by niemasd** [comment]
Great, thanks! I won't be home for another two days, but I'll test it out and let you know once I'm back!

**Comment by niemasd** [comment]
It works great!!! Thanks so much!
